# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion = "${fml_range}" #mandatory (27 is current forge version)

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "GPL3"

# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/ldtteam/minecolonies/issues/new/choose" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "minecolonies" #mandatory

# The version number of the mod
version = "${version}" #mandatory

# A display name for the mod
displayName = "MineColonies" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://minecolonies.com" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "minecolonies_logo.png" #optional

# A text field displayed in the mod UI
credits = "All the coffees!" #optional

# A text field displayed in the mod UI
authors = "LDT Team" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''
MineColonies is a colony simulator within Minecraft! There are numerous types of workers, and each worker has its own type of hut, letting you build a busy and vibrant village/town/city/colony. There is no coded limit to the number of NPC's at your disposal, so you can create a small, efficient village dedicated to a particular type of worker or a sprawling metropolis with hundreds of workers. It's entirely up to you!
'''

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.minecolonies]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[${forgeMinVersion}, )" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "structurize"
type = "required"
versionRange = "[${structurize_version}, )"
ordering = "AFTER"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "blockui"
type = "required"
versionRange = "[${blockUI_version}, )"
ordering = "AFTER"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "domum_ornamentum"
type = "required"
versionRange = "[${domumOrnamentumVersion}, )"
ordering = "AFTER"
side = "BOTH"
[[dependencies.minecolonies]]
modId = "journeymap"
type = "optional"
versionRange = "[${jmapVersion},)"
ordering = "NONE"
side = "BOTH"
